# Generated by Django 5.2.8 on 2025-11-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedimage',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Optional id from external API (e.g. unsplash id).', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('source', models.CharField(blank=True, help_text='Optional source name (Unsplash/Custom)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='pinterest_A_externa_3a1479_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='pinterest_App.image'),
        ),
        migrations.AlterUniqueTogether(
            name='savedimage',
            unique_together={('user', 'image')},
        ),
        migrations.RemoveField(
            model_name='savedimage',
            name='post',
        ),
    ]
